import type { Metadata } from "next";
import Navbar from "@/brand/components/misc/navbar";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import SmoothScrolling from "./_components/smooth-scrolling";

const spacGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Playcope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spacGrotesk.variable} antialiased font-sans overflow-x-hidden`}
      >
        <SmoothScrolling>
          <header className="container sticky z-50 md:p-3 px-3 mx-auto top-5">
            <Navbar />
          </header>
          {children}
        </SmoothScrolling>
      </body>
    </html>
  );
}
