import type { Metadata } from "next";
import Navbar from "@/brand/components/misc/navbar";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const spacGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Playcope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spacGrotesk.variable} antialiased font-sans`}>
        <header className="container sticky z-50 p-3 mx-auto top-5">
          <Navbar />
        </header>
        {children}
      </body>
    </html>
  );
}
