import type { Metadata } from "next";
import Navbar from "@/brand/components/misc/navbar";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";

const spacGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Playcope",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${spacGrotesk.variable} antialiased font-sans`}>
        <header className="container sticky z-50 md:p-3 px-3 mx-auto top-5">
          <Navbar />
        </header>
        {children}
        <svg className="absolute pointer-events-none" width="0" height="0">
          <defs>
            <filter
              id="glass-distort"
              x="-50%"
              y="-50%"
              width="200%"
              height="200%"
            >
              {/* Very low frequency turbulence creates smooth, large waves for clear lens effect */}
              <feTurbulence
                type="fractalNoise"
                baseFrequency="0.02"
                numOctaves="2"
                result="turbulence"
              />
              {/* Apply smooth displacement to create clear lens refraction - bends straight lines into curves */}
              <feDisplacementMap
                in="SourceGraphic"
                in2="turbulence"
                scale="45"
                xChannelSelector="R"
                yChannelSelector="G"
              />
            </filter>
          </defs>
        </svg>
      </body>
    </html>
  );
}
